

name: Pipeline CI with Maven

on:
  push:
    branches: [ "master" ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Téléchargement des sources
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Verify libs directory
      run: ls -la ${GITHUB_WORKSPACE}/libs

    - name: Install dependencies
      run: mvn install 

    - name: Compile the code
      run: mvn compile
  
    - name: Run tests
      run: mvn test
  
    - name: Package application
      run: mvn package -DskipTests

   