

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  

jobs:
  compile:

    runs-on: ubuntu-latest

    steps:
    - name: Téléchargement des sources
      uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Install dependencies
      run: mvn install -DskipTests
  
    - name: Run tests
      run: mvn test
  
    - name: Package application
      run: mvn package

   